name: Build Windows App

on:
  push:
    branches:
      - main  # Change if using another branch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter (3.29.0)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'  # Ensures Dart 3.7.0+
          cache: false  # Avoid using cached older versions

      - name: Enable Windows Support
        run: |
          flutter config --enable-windows-desktop
          flutter doctor

      - name: Ensure Windows Project Exists
        run: |
          if [ ! -d "windows" ]; then
            flutter create .
          fi

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/runner/Release/
