name: Build Windows App

on:
  push:
    branches:
      - main  # Change this if using another branch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter (Latest Stable)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'  # Use latest stable Flutter version (includes Dart 3.7+)
          cache: false  # Avoid using cached older versions

      - name: Verify Flutter & Dart Version
        run: |
          flutter --version
          dart --version
          flutter doctor

      - name: Enable Windows Support
        run: flutter config --enable-windows-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/runner/Release/
