name: Build Windows App

on:
  push:
    branches:
      - main  # Change if using another branch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter (3.29.0)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          cache: false

      - name: Enable Windows Support
        run: |
          flutter config --enable-windows-desktop
          flutter doctor

      - name: Debug Project Structure
        run: Get-ChildItem -Path . -Recurse

      - name: Generate Windows Folder (If Missing)
        shell: pwsh
        run: |
          if (-Not (Test-Path "windows")) {
            flutter create .
          }

      - name: Install Dependencies
        run: flutter pub get

      - name: Debug Build Process
        run: flutter build windows --verbose || exit 1

      - name: Debug Build Output
        run: Get-ChildItem -Path build/windows -Recurse

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/runner/
